Pages/Index.cshtml.cs
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace razorApp.Pages;
    public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    private readonly HttpClient _httpClient;

    public IndexModel(ILogger<IndexModel> logger, HttpClient httpClient)
    {
        _logger = logger;
        _httpClient = httpClient;
    }

    public void  OnGet()
    {

    }
}

Pages/analiseService.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http;
using System.Text.Json;
using razorApp.models;
namespace razorApp.Pages;


    public class AnaliseService : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly HttpClient _httpClient;

    public string[] MinhaString { get; set; }

    // public Service[] MeuService {get;set;}


    public AnaliseService(ILogger<IndexModel> logger, HttpClient httpClient)
    {
        _logger = logger;
        _httpClient = httpClient;
    }

    public async Task OnGet()
    {
            // var response = await _httpClient.GetAsync("https://localhost:7003/service");
            // response.EnsureSuccessStatusCode();
            // var result= await response.Content.ReadAsStringAsync();
            // // MinhaString= result;
            // MeuService = JsonSerializer.Deserialize<Service[]>(result);

            // foreach (var item in MeuService)
            // {
            //     Console.WriteLine(item.name);
            // }

            // MeuService = JsonSerializer.Deserialize<List<ServiceModel>>(result);
    }
}

Pages/cadService.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Net.Http;
using razorApp.models;
using System.Text;
using System.Text.Json;
using System.Diagnostics;
using razorApp.data;
using Microsoft.EntityFrameworkCore;
using razorApp.repositories;
using razorApp.models;

namespace razorApp.Pages;

public class Service : PageModel

{
    private readonly ILogger<IndexModel> _logger;

    public string Message { get; set; }
    private readonly ServiceDBContext _serviceDBContext;

    public Service(ILogger<IndexModel> logger, ServiceDBContext serviceDBContext)
    {
        _logger = logger;
        _serviceDBContext = serviceDBContext;
    }
    public ServiceModel[] MeuService { get; set; }

    [BindProperty]
    public ServiceModel? service { get; set; }

    public async Task OnGetAsync()
    {
        var result = await _serviceDBContext.Services.OrderBy(s => s.id).ToListAsync();
        MeuService = result.ToArray();
    }

public async Task<IActionResult> OnPostPutServiceAsync(ServiceModel serviceUpdated)
{
    if (Request.Form["_method"] == "PUT")
    {
        var service1 = await _serviceDBContext.Services.FindAsync(serviceUpdated.id);
        if (service1 != null)
        {
            service1.name = serviceUpdated.name;
            service1.date = serviceUpdated.date;
            service1.service = serviceUpdated.service;
            service1.value = serviceUpdated.value;
            service1.contact = serviceUpdated.contact;
            service1.id=serviceUpdated.id;

            await _serviceDBContext.SaveChangesAsync();
        }
        else
        {
            return NotFound();
        }
        return RedirectToPage("./cadService");
    }
    else
    {
        return StatusCode(405);
    }
}

    public async Task<IActionResult> OnPostEnviarAsync([FromForm] ServiceModel serviceModel)
    {
        try
        {
            // return RedirectToPage("/Forms/Strategy");
            // if (!ModelState.IsValid)
            // {
            //     foreach (var modelState in ModelState.Values)
            //     {
            //         foreach (var error in modelState.Errors)
            //         {
            //             Console.WriteLine($"Model Error: {error.ErrorMessage}");
            //         }
            //     }


            // }
            await _serviceDBContext.Services.AddAsync(serviceModel);
            await _serviceDBContext.SaveChangesAsync();
            return RedirectToPage("./cadService");

        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Erro durante o processamento OnPostAsync");
            return StatusCode(500);
        }

    }

    public async Task<IActionResult> OnPostDeleteAsync(int id)
    {
        try
        {
            Console.WriteLine(id);
            var service = await _serviceDBContext.Services.FindAsync(id);

            if (service != null)
            {
                _serviceDBContext.Services.Remove(service);
                await _serviceDBContext.SaveChangesAsync();
            }
            return RedirectToPage("./cadService");

        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Erro durante o processamento do remove");
            return StatusCode(500);
        }

    }

    public async Task<IActionResult> OnPostUpdateAsync(int id)
    {
        try
        {
            Console.WriteLine(id);
            var service = await _serviceDBContext.Services.FindAsync(id);

            if (service != null)
            {
                _serviceDBContext.Services.Update(service);
                await _serviceDBContext.SaveChangesAsync();
            }
            return RedirectToPage("./cadService");

        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Erro durante o processamento do remove");
            return StatusCode(500);
        }

    }

}

// [FromForm] ServiceModel serviceModel

// Console.WriteLine("IF2");
// Console.WriteLine(model);
// Console.WriteLine($"Model: {model}");

// [FromForm]ServiceModel model

    // string htmlContent = "<h1>Hello, World!</h1>";

    // // Create a ContentResult with your HTML content
    // ContentResult contentResult = new ContentResult
    // {
    //     Content = htmlContent,
    //     ContentType = "text/html"
    // };

    // // Return the ContentResult
    // return contentResult;

Pages/formService.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Net.Http;
using razorApp.models;
using System.Text;
using System.Text.Json;
using System.Diagnostics;
using razorApp.data;
using Microsoft.EntityFrameworkCore;

namespace razorApp.Pages;

    public class formService : PageModel
{
    private readonly ILogger<IndexModel> _logger;


    private readonly HttpClient _httpClient;
    public ServiceModel[] MeuService {get;set;}

    [BindProperty]
    public ServiceModel service {get;set;}

    private readonly ServiceDBContext _serviceDBContext;

    public formService(ILogger<IndexModel> logger, HttpClient httpClient1, ServiceDBContext serviceDBContext)
    {
        _logger = logger;
        _httpClient = httpClient1;
        _serviceDBContext= serviceDBContext;
    }

    public async Task OnGetAsync()
    {
    }
    
    public async Task<IActionResult> OnPostEnviarAsync([FromForm] ServiceModel serviceModel)
    {
        try
        {
            // return RedirectToPage("/Forms/Strategy");
            // if (!ModelState.IsValid)
            // {
            //     foreach (var modelState in ModelState.Values)
            //     {
            //         foreach (var error in modelState.Errors)
            //         {
            //             Console.WriteLine($"Model Error: {error.ErrorMessage}");
            //         }
            //     }


            // }
            await _serviceDBContext.Services.AddAsync(serviceModel);
            await _serviceDBContext.SaveChangesAsync();

            TempData["AlertMessage"] = "Serviço adicionado com sucesso!";

            return RedirectToPage("./formService");

        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Erro durante o processamento OnPostAsync");
            return StatusCode(500);
        }

    }

// public async Task<IActionResult> onPostEnviarAsync(){

//     if (!ModelState.IsValid)
//     {
//         return Page();
//     }
//     var service1= new ServiceModel();
//     var response = await _httpClient.PostAsJsonAsync("https://localhost:7003/service", service1);
  
//         return Page();
//     }
}

Pages/Index.cshtml
@page
@model razorApp.Pages.IndexModel
@{
    ViewData["Title"] = "Index";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Gestão de serviços Razor</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="~/">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Serviços
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="~/formService"href="~/cadService">Serviços- Cadastro</a></li>
                            <li><a class="dropdown-item" href="~/cadService">Serviços- Relação</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="~/analiseService">Relatório de acompanhamento</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<body>
</br>
<h3 style="margin-left:5%;">Bem vindo ao melhor app de gestão de serviços</h3>
</br>


<div style="margin-left:5%;display:flex;">
<form>
    <div class="form-group" >
        <label for="exampleInputEmail1"  >User</label>
        <input style="display:flex;" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Insira o email." name="email">
<!--        <small id="emailHelp" class="form-text text-muted">Nome completo.</small>-->
    </div>
    </br>
    <div class="form-group">
        <label>Password</label>
        <input tyle="display:flex;" type="password" class="form-control" placeholder="Insira a senha." name="password">
    </div>
    </br>
<!--    <div class="form-check">-->
<!--        <input type="checkbox" class="form-check-input" id="exampleCheck1">-->
<!--        <label class="form-check-label" for="exampleCheck1">Check me out</label>-->
<!--    </div>-->
    <button type="submit" class="btn btn-primary">Login</button>
</form>
<br><br><br><br><br>
</div>
<div style="margin-top: 5%">
<img src="~/Assets/FarQGLEaQAAD_Hm.jpeg" height="500px">
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>

</html>


@* <div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div> *@

Pages/cadService.cshtml
@page
@model razorApp.Pages.Service;
@{
    ViewData["Title"] = "cadService";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Gestão de serviços Razor</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="~/">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Serviços
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="~/formService"href="~/cadService">Serviços- Cadastro</a></li>
                            <li><a class="dropdown-item" href="~/cadService">Serviços- Relação</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="~/analiseService">Relatório de acompanhamento</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<body>
</br>
<h3>Bem vindo ao melhor app de gestão de serviços</h3>
</br>
         @* <form method="post">
            <div class="form-group" >
                <label asp-for="service.name">Cliente</label>
                <input type="text" class="form-control" name="name" asp-for="service.name" placeholder="Insira o nome." />
        <!--        <small id="emailHelp" class="form-text text-muted">Nome completo.</small>-->
            </div>
            </br>
            <div class="form-group">
                <label asp-for="service.contact">Telefone</label>
                <input type="number" class="form-control" name="contact" asp-for="service.contact" placeholder="Insira o telefone."/>
            </div>
            </br>
            <div class="form-group">
                <label asp-for="service.service">Serviço</label>
                <input type="text" class="form-control" name="service" asp-for="service.service" placeholder="Insira o Serviço."/>
            </div>
            </br>
            <div class="form-group">
                <label asp-for="service.value">Valor</label>
                <input type="number" class="form-control" name="value" asp-for="service.value" placeholder="Insira o Valor."/>
            </div>
            </br>
            <div class="form-group">
                <label asp-for="service.date">Data</label>
                <input type="month" class="form-control" name="date" asp-for="service.date" placeholder="Insira a Data."/>
            </div>
            <button class="btn btn-primary" type="submit">Gravar</button>
            </form> *@

<!-- Button trigger modal -->


@* <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target=".bd-example-modal-lg">Relação de serviços</button> *@
<br></br>

        <table class="table" style="width: 70%">
    <thead>
    <tr>
        <th scope="col">Nome</th>
        <th scope="col">Contato</th>
        <th scope="col">Serviço</th>
        <th scope="col">Valor</th>
        <th scope="col">Data</th>
        <th scope="col">Editar</th>
        <th scope="col">Deletar</th>
    </tr>
    </thead>
    <tbody>
        @for (int i= 0; i < Model.MeuService.Length; i++)
        {
            <tr>
            <td scope="row">@Model.MeuService[i].name</td>
            <td scope="row">@Model.MeuService[i].contact</td>
            <td scope="row">@Model.MeuService[i].service</td>
            <td scope="row">@Model.MeuService[i].value</td>
            <td scope="row">@Model.MeuService[i].date</td>
            <input type="hidden" value="@Model.MeuService[i].id" name="ServiceID">
            <td><button style="border:none;" onclick="abrirModal(@Model.MeuService[i].id)"> <i class="bi bi-pencil-fill"></i> </button></td>
            <td><form method="post"><button style="border:none;"type="submit" asp-page-handler="Delete" asp-route-id="@Model.MeuService[i].id"><i class="bi bi-trash3-fill" style="background-color:aliceblue;"></i></button></form></td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="staticBackdrop" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tela de edição</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="display:flex;margin-left: 20%;">  
         <form method="post" asp-page-handler="PutService">
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" name="id">
            <div class="form-group" >
                <label>Cliente</label>
                <input type="text" class="form-control" name="name" asp-for="service.name" placeholder="Insira o nome." />
        <!--        <small id="emailHelp" class="form-text text-muted">Nome completo.</small>-->
            </div>
            </br>
            <div class="form-group">
                <label>Telefone</label>
                <input type="number" class="form-control" name="contact" asp-for="service.contact" placeholder="Insira o telefone."/>
            </div>
            </br>
            <div class="form-group">
                <label>Serviço</label>
                <input type="text" class="form-control" name="service" asp-for="service.service" placeholder="Insira o Serviço."/>
            </div>
            </br>
            <div class="form-group">
                <label >Valor</label>
                <input type="number" class="form-control" name="value" asp-for="service.value" placeholder="Insira o Valor."/>
            </div>
            </br>
            <div class="form-group">
                <label>Data</label>
                <input type="month" class="form-control" name="date" asp-for="service.date" placeholder="Insira a Data."/>
            </div>
            <br>
            <button class="btn btn-primary" asp-page-handler="PutService" type="submit">Gravar</button>
           </form>
      </div>
      <div class="modal-footer">
        @* <p>@Model.Message</p>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button> *@
      </div>

    </div>
  </div>
</div>




    @* <script>
        document.querySelector('#meuFormulario').addEventListener('submit', function (event) {
            event.preventDefault();
            
            var valorCampo = document.querySelector('#meuFormulario').value;
            console.log(valorCampo);
        });
    </script> *@
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
<script>
    function abrirModal(serviceId) {
            var myModal = new bootstrap.Modal(document.getElementById('staticBackdrop'));
            myModal.show();
            console.log(serviceId);
            document.getElementsByName("id")[0].value= serviceId;
                        @* document.getElementsByName("id")[0].value= document.getElementsByName("ServiceID")[0].value; *@
  }
</script>

</body>

</html>



@* <form method="get">
    <input type="hidden" name="handler" value="Outro" />
    <button type="submit">Chamar método OnGetOutro</button>
</form> *@

Pages/formService.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers   
@model razorApp.Pages.formService
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Gestão de serviços Razor</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="~/">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Serviços
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="~/formService"href="~/cadService">Serviços- Cadastro</a></li>
                            <li><a class="dropdown-item" href="~/cadService">Serviços- Relação</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="~/analiseService">Relatório de acompanhamento</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<body>


         <form method="post" asp-page-handler="Enviar" style="margin-left:5%;">
         <h2>Cadastro de Serviço</h2>
            <div class="form-group" >
                <label asp-for="service.name">Cliente</label>
                <input type="text" class="form-control" name="name" asp-for="service.name" placeholder="Insira o nome." style="width: 30%"/>
        <!--        <small id="emailHelp" class="form-text text-muted">Nome completo.</small>-->
            </div>
            </br>
            <div class="form-group">
                <label asp-for="service.contact">Telefone</label>
                <input type="tel" class="form-control" name="contact" asp-for="service.contact" placeholder="Insira o telefone." style="width: 30%"/>
            </div>
            </br>
            <div class="form-group">
                <label asp-for="service.service">Serviço</label>
                <input type="text" class="form-control" name="service" asp-for="service.service" placeholder="Insira o Serviço." style="width: 30%"/>
            </div>
            </br>
            <div class="form-group">
                <label asp-for="service.value">Valor</label>
                <input type="number" class="form-control" name="value" asp-for="service.value" placeholder="Insira o Valor." style="width: 30%"/>
            </div>
            </br>
            <div class="form-group">
                <label asp-for="service.date">Data</label>
                <input type="month" class="form-control" name="date" asp-for="service.date" placeholder="Insira a Data." style="width: 30%"/>
            </div>
            <button class="btn btn-primary" type="submit">Gravar</button>
            </form>
            <br>
            <br>
            @if (!string.IsNullOrEmpty(TempData["AlertMessage"] as string))
            {
                <div class="alert alert-success" role="alert">
                    @Html.Raw(TempData["AlertMessage"])
                </div>
            }

            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>